---
- name: CONFIGURE DEVICES
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "config.yml"
    - "secrets.yml"
    - "common.yml"

  pre_tasks:
    - name: CREATE CONFIGURATION DIRECTORY
      file: path={{base_dir}}/{{configs}} state=directory
    - name: CREATE NODE CONFIGURATION DIRECTORY
      file: path={{base_dir}}/{{configs}}/{{inventory_hostname}} state=directory

  tasks:
    - name: LOAD PARAMETERS
      include_vars:
        file: "{{base_dir}}/{{devices}}/{{inventory_hostname}}.yml"

    - name: CREATE CONFIGURATIONS
      template: src={{item.src}} dest={{base_dir}}/{{configs}}/{{inventory_hostname}}/{{inventory_hostname}}-{{(item.src | basename | splitext)[0]}}.conf
      with_filetree: "{{base_dir}}/{{templates}}"
      when: item.state == 'file'

    - name: SET MASTER CONFIG NAME
      set_fact: master_config={{base_dir}}/{{configs}}/{{inventory_hostname}}-{{target | default('test')}}-startup-config

    - name: MERGE IN A SINGLE FILE
      assemble:
        src: "{{base_dir}}/{{configs}}/{{inventory_hostname}}"
        dest: "{{master_config}}"
    #track if diff

    - name: DEFINE IOS PROVIDER
      set_fact:
        provider:
          host: "{{hostvars[inventory_hostname]['ansible_host']}}"
          username: "{{creds['username']}}"
          password: "{{creds['password']}}"
      when: os == "ios"

    - name: UPLOAD CANDIDATE CONFIG TO IOS DEVICE
      local_action: >
        command /usr/bin/sshpass -p {{creds['password']}} /usr/bin/scp "{{master_config}}" {{creds['username']}}@{{hostvars[inventory_hostname]['ansible_host']}}:{{dest_device}}:/candidate-config
      when: os == "ios"
      # only when above file diff

      #    - name: REPLACE CURRENT CONFIG WITH CANDIDATE CONFIG
      #ios_config:
      #  provider: "{{ provider }}"
      #  commands:
      #    - "configure replace {{dest_device}}:/candidate-config force"
      #  authorize: yes
      #  timeout: 120
      #register: replace_config_output
  
#    - name: DEBUG
#      debug:
#        var: replace_config_output


