---
- name: VALIDATE CONFIGURATION
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "config.yml"
    - "secrets.yml"
    - "common.yml"

  tasks:
    - name: LOAD PARAMETERS
      include_vars:
        file: "{{base_dir}}/{{devices}}/{{inventory_hostname}}.yml"

    - name: TESTING REACHABILITY
      ping:

    - name: DEFINE IOS PROVIDER
      set_fact:
        provider:
          host: "{{hostvars[inventory_hostname]['ansible_host']}}"
          username: "{{creds['username']}}"
          password: "{{creds['password']}}"
      when: os == "ios"

    - name: TESTING CONNECTIVITY
      ios_command:
        provider: "{{ provider }}"
        commands:
          - "ping 10.0.12.1 source Loopback0"
          - "ping 10.0.12.2 source Loopback0"
          - "ping 10.0.23.2 source Loopback0"
          - "ping 10.0.23.3 source Loopback0"
          - "ping 10.255.255.1 source Loopback0"
          - "ping 10.255.255.2 source Loopback0"
          - "ping 10.255.255.3 source Loopback0"
        authorize: yes
      when: os == "ios"
