---
- name: SET IOS PROVIDER
  set_fact:
    provider:
      host: "{{hostvars[inventory_hostname]['ansible_host']}}"
      username: "{{ansible_username}}"
      password: "{{ansible_password}}"
      transport: cli
      timeout: 600
- name: EXECUTE CISCO_NXOS ROLE
  connection: local
  nxos_command:
    provider: "{{provider}}"
    commands:
      - "show version"
      - "show inventory"
      - "show running-config"
      - "show tech-support"
  register: result
- local_action: copy content="{{result.stdout[0]}}\n" dest={{repo}}/show_version
- local_action: copy content="{{result.stdout[1]}}\n" dest={{repo}}/show_inventory
- local_action: copy content="{{result.stdout[2]}}\n" dest={{repo}}/running-config
- local_action: copy content="{{result.stdout[3]}}\n" dest={{repo}}/tech-support

