---
- name: DISCOVER DEVICES
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "config.yml"
  pre_tasks:
    - set_fact:
        repo: "{{base_dir}}/devices/{{inventory_hostname}}"
    - name: CREATE CONFIGURATION DIRECTORY
      file: path={{repo}} state=directory

- hosts: cisco_l2_switches
  gather_facts: no
  roles:
    - cisco_ios
    - cisco_ios_l2switch
